#! /usr/bin/env bash

FILE="file.txt"

echo "" > "$FILE"
for (( i=0; i < 500; i++ )); do
  echo "$i " >> "$FILE"
done

TO_SORT=$(cat "$FILE" | sort -R | paste -sd ' ')
rm "$FILE"

./push_swap $TO_SORT
# valgrind --leak-check=yes ./push_swap $TO_SORT
